services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_DATABASE: sample_api_development
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "
        whenever --update-crontab &&
        cron &&
        bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/sample-api
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data: