default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: sample_api_development

test:
  <<: *default
  database: sample_api_test

production:
  <<: *default
  database: sample_api_production
  username: sample_api
  password: <%= ENV["SAMPLE_API_DATABASE_PASSWORD"] %>
