- question: "ファイルの一覧を表示するコマンドは？"
  choices:
    - "cd"
    - "ls"
    - "mkdir"
  answer: "ls"
- question: "現在のディレクトリを表示するコマンドは？"
  choices:
    - "cd"
    - "ls"
    - "pwd"
  answer: "pwd"
- question: "指定したディレクトリに移動するコマンドは？"
  choices:
    - "cd"
    - "ls"
    - "mkdir"
  answer: "cd"
- question: "ファイルがない場合に新規作成するコマンドは？"
  choices:
    - "cd"
    - "touch"
    - "mkdir"
  answer: "touch"
- question: "ディレクトリを作成するコマンドは？"
  choices:
    - "cd"
    - "ls"
    - "mkdir"
  answer: "mkdir"
- question: "ファイルを削除するコマンドは？"
  choices:
    - "rm"
    - "ls"
    - "mkdir"
  answer: "rm"
- question: "空のディレクトリを削除するコマンドは？"
  choices:
    - "cd"
    - "rmdir"
    - "mkdir"
  answer: "rmdir"
- question: "ファイルやディレクトリをコピーするコマンドは？"
  choices:
    - "cd"
    - "cp"
    - "mkdir"
  answer: "cp"
- question: "ファイルを検索するコマンドは？"
  choices:
    - "find"
    - "ls"
    - "mkdir"
  answer: "find"
- question: "ファイルの中身を表示するコマンドは？"
  choices:
    - "cd"
    - "cat"
    - "mkdir"
  answer: "cat"